export const metadata = {
    title: 'Dashboard || Next Hero',
    description: 'Generated by sazzad',
}
const dashboardLayout = ({ children }) => {
    return (
        <div>
            <div>Sidebar</div>
            {children}
        </div>
    );
};

export default dashboardLayout;