export const metadata = {
    title: 'DashBoard||Next Hero',
    description: 'Generated by sazzad',
}

const DashboardPage = () => {
    return (
        <div>
            Dashboard Page
        </div>
    );
};

export default DashboardPage;