export const metadata = {
    title: 'Add product || Next Hero',
    description: 'Generated by sazzad',
}

const AddProductPage = () => {
    return (
        <div>
            add product page
        </div>
    );
};

export default AddProductPage;