import Link from "next/link";


export const metadata = {
    title: 'blogs||Next Hero',
    description: 'Generated by sazzad',
}
// const blogs = [
//     {
//         id: 1,
//         year: 2016,
//         title: "Title 1"
//     },
//     {
//         id: 2,


//         year: 2016,
//         title: "Title 2"
//     },
//     {
//         id: 3,
//         year: 2016,
//         title: "Title 3"
//     },
//     {
//         id: 4,
//         year: 2016,
//         title: "Title 4"
//     },
//     {
//         id: 5,
//         year: 2016,
//         title: "Title 5"
//     },
// ]

const BlogsPage = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts", {
        cache: "force-cache"
    })
    const blogs = await res.json()

    return (
        <div className="container mx-auto">
            {
                blogs.map(({ id, title, body }) => {
                    return (
                        <div key={id} className=" border border-blue-500 p-2 my-2">
                            <h2 className="text-2xl">{id}. {title} </h2>
                            <p>{body}</p>
                            <Link className="inline-block mt-5" href={`/blogs/${id}`}><button className="shadow-lg text-white px-2 py-1 bg-blue-500 ">Details</button></Link>


                        </div>
                    )
                }
                )
            }
        </div>
    );
};

export default BlogsPage;