// 'use client'
import Link from "next/link";
// import { useRouter } from "next/navigation";

export const metadata = {
    title: 'blogs||Next Hero',
    description: 'Generated by sazzad',
}
const blogs = [
    {
        id: 1,
        year: 2016,
        title: "Title 1"
    },
    {
        id: 2,


        year: 2016,
        title: "Title 2"
    },
    {
        id: 3,
        year: 2016,
        title: "Title 3"
    },
    {
        id: 4,
        year: 2016,
        title: "Title 4"
    },
    {
        id: 5,
        year: 2016,
        title: "Title 5"
    },
]

const BlogsPage = () => {
    // const router = useRouter()
    return (
        <div className="container mx-auto">
            {
                blogs.map(({ id, year, title }) => {
                    return (
                        <Link
                            className="block border border-blue-500 p-2 my-2"
                            href={{
                                pathname: `/blogs/${year}/${id}`,
                                query: {
                                    title: title
                                }
                            }}
                            // onClick={() => router.push(`/blogs/${year}/${id}?title=${title}`)}
                            key={id}>
                            {title}
                        </Link>
                    )
                }
                )
            }
        </div>
    );
};

export default BlogsPage;