export const metadata = {
    title: 'Profile||Next Hero',
    description: 'Generated by sazzad',
}

const ProfilePage = () => {
    return (
        <div>
            <h1>this is profile page</h1>
        </div>
    );
};

export default ProfilePage;