
import { defaults } from 'autoprefixer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'next hero',
  description: 'Generated by sazzad',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <a href='/'>home</a>
        </nav>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  )
}


